### ISSUE TITLE
[1.15.2 v1.1.3] Sometimes stops advancements/deaths from getting sent to in-game chat

### ISSUE THREAD

**Issue by shortybsd** [Denis3d/Minecraft2Discord#33] opened 2020-03-10 20:24 UTC
Forge version 31.1.18
Minecraft2Discord version 1.15.2-1.1.3

Every other advancement a player makes does not get sent to in-game chat. This mod sometimes blocks it from being sent as well as deaths and anything else related to a player. It catches the event yet blocks Minecraft's event being sent to chat.

**Comment by Denis3d** [comment] 2020-03-11 13:27
Hi,
Thanks for reporting. Is it possible to have more information? What's the list of mods that is installed, did you have any error in the console?

**Comment by shortybsd** [comment] 2020-03-11 18:08
Thank you Denis for responding. I currently do not see anything in the logs with any Minecraft2Discord errors. I removed Lithium as I saw it was not needed, the server runs smooth as silk without it also might have been the culprit. [Here is the modlist](https://pastebin.com/9mmaDykt)
I haven't noticed it skipping things out of Minecraft chat since I removed Lithium.

**Comment by Denis3d** [comment] 2020-03-11 19:50
If the issue is resolved, it means that the issue is coming from it... Can you confirm that the issue is resolved? If it is and if you want to play with lithium installed, let me know it and I will try to reach lithium devs in order to find the origin of the issue

**Comment by shortybsd** [comment] 2020-03-11 20:11
Yes, the issue stemmed from Lithium. I removed it and no issues yet. Closing this, if I decide to run Lithium in the long run I will get a hold of the dev. Thanks again and sorry for this report.

**Comment by Denis3d** [comment] 2020-03-12 06:08
There's nor problem for reporting... It's sometimes difficult to see from where is coming the problem.

**Comment by shortybsd** [comment] 2020-03-12 21:51
Ok it is still doing it. No errors on server, nor client. Here is an example
Tail of server log:
 `[12Mar2020 16:39:05.296] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: <shortybsd> yeah i am good
[12Mar2020 16:39:15.217] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: <shortybsd> dude this is freaking awesome !~
[12Mar2020 16:43:39.934] [Server thread/INFO] [morpheus/]: frankieleft is now sleeping. 1/2 - 2 miners (100%)
`

[Screenshot of Discord](https://imgur.com/wLjsyTX)

[Screenshot of Minecraft Client](https://imgur.com/FqvlFCC)

**Comment by Denis3d** [comment] 2020-03-13 09:14
So your problem is just the advancement that is not sent in the server chat but relayed in Discord? I can't see anythings causing that in the code... If you remove only minecraft2discord is the advancement send in the server chat?
If you want you can join my discord so it's easier for us to chat : https://discord.gg/rzzd76c

**Comment by Darkere** [comment] 2020-03-14 13:25
That's what happens to invisible advancements. as per #31

**Comment by Denis3d** [comment] 2020-03-14 13:27
Isn't exactly the same case while here the advancement is suppose to be displayed on both side but it's displayed only on discord.

**Comment by Darkere** [comment] 2020-03-14 13:33
You are sending a message to Discord for every advancement here: https://github.com/Denis3d/Minecraft2Discord/blob/3af7c4e9944e154fd1b933669e23c07ba222b958/src/main/java/ml/denis3d/minecraft2discord/events/ServerEvents.java#L97

Minecraft handles advancements for the in-game chat by itself. It filters out any advancements that are supposed to be hidden. 
Like that you end up with the situation above.

**Comment by Denis3d** [comment] 2020-03-14 13:43
Yeah but in this case minecraft is hiding advancement that is supposed to be show

**Comment by Denis3d** [comment] 2020-03-19 21:17
I'm closing this as there is no answer from the issue owner for 1 week

**Closed by Denis3d** 2020-03-19 21:17 UTC
