### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by IchigoGames** [Denis3d/Minecraft2Discord#16] opened 2019-09-02 18:47 UTC
Minecraft 1.14.4
Forge 28.0.82
minecraft2discord-1.14.4-1.0.6

What happens Server Crashes wish i could give more info but im not sure why all i can see 
in the crash log is it looks like your bot got advancement and then crashed server here is the crash report https://pastebin.com/zx1ac6Ei if you need more logs let me know.

**Comment by Denis3d** [comment] 2019-09-02 20:33
Seem to be the same bug that #15 
Acording to the logs you send you are still in 1.0.**5**
I fix a bug in 1.0.6 that wasn't reported at this time. I can't see any thing else that can make this crash.
While I can't reproduce this bug I can't investigate further.
Please update to the last version and feel free to reopen this issue if your server crash again

**Comment by IchigoGames** [comment] 2019-09-03 01:38
https://pastebin.com/buUrezE5 sorry mabey i sent the wrong crash report after it happend the first time i updated and did not report it thinking it was fixed but its not I Am using minecraft2discord-1.14.4-1.0.6

**Comment by IchigoGames** [comment] 2019-09-03 01:39
can you please Reopen this or the first one

**Comment by Denis3d** [comment] 2019-09-03 08:02
Can you please describe the step to reproduce this bug. I can't resolve this problem while I can't find it and reproduce it.

**Comment by IchigoGames** [comment] 2019-09-03 16:38
i think it happend when some one cut down a tree but truth be told not sure all i know is it looks like to me the bot some how got a advancement if i get more info ill let you know

**Comment by Denis3d** [comment] 2019-09-03 16:54
While it's not the same advancement as #15 I think this can happen for any advancement. I can't figure out where the bug is coming from while I can't reproduce it.
Is the server running for a while when crash ?
Is it always the same advancement ?

**Comment by IchigoGames** [comment] 2019-09-03 17:26
Yes and im not sure what advancement is causing it

**Comment by Denis3d** [comment] 2019-09-11 15:03
I test a bug fix in 1.0.7 ! 
Can you test this new version and send the new crash report if the bug is still present 🤞.
If not 😃 I will let you close this issue

**Comment by IchigoGames** [comment] 2019-09-11 15:33
ok ill give it a try

**Comment by IchigoGames** [comment] 2019-09-11 16:09
It Works now thank you

**Comment by IchigoGames** [comment] 2019-09-11 22:59
sorry not fixed i forgot what the crash was on here it just crashed https://pastebin.com/4RHBLa5R

**Comment by Denis3d** [comment] 2019-09-12 06:02
Seem to be another issue...
Did you have the info Channel ID in your config...

**Closed** 2019-09-20 19:49 UTC
Labels: duplicate
